### 1. Obtener la lista de tareas (GET)
GET http://localhost:8080/api/tasks

### 2. Crear una nueva tarea (POST)
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "titulo": "Completar la práctica de Spring Boot"
}

### 3. Actualizar
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "titulo": "Terminar la práctica",
  "estado": "EN PROGRESO"
}

### 4. Eliminar
DELETE http://localhost:8080/api/tasks/1